from django.urls import path
from .views import (
    dashboard_home,
    page_speed_insights,
    analysis_detail,
    AnalysisListView,
    delete_analysis,
    bulk_delete_pagespeed_analyses,
    extract_headers_view,
    header_analysis_list,
    header_analysis_detail,
    delete_header_analysis,
    bulk_delete_header_analyses,
    image_alt_finder,
    image_alt_list,
    image_alt_detail,
    delete_image_alt_analysis,
    bulk_delete_image_alt_analyses,
    keywords_finder,
    keywords_list,
    keywords_detail,
    delete_keyword_analysis,
    bulk_delete_keyword_analyses,
    connect_gsc,
    gsc_callback,
    disconnect_gsc,
    ai_search_overview,
    ai_readiness_audit,
    ai_readiness_detail,
    delete_ai_readiness,
    bulk_delete_ai_readiness,
    ai_question_research,
    ai_citation_opportunities,
)
from .pdf_report_views import (
    pdf_reports_list,
    generate_pdf_report,
    pdf_report_detail,
    preview_pdf_report,
    download_pdf_report,
    delete_pdf_report,
    bulk_delete_pdf_reports,
    regenerate_pdf_report,
)

app_name = "dashboard"

urlpatterns = [
    path("", dashboard_home, name="home"),
    path("page-speed-insights/", page_speed_insights, name="page_speed_insights"),
    path("analysis/<int:pk>/", analysis_detail, name="analysis_detail"),
    path("analyses/", AnalysisListView.as_view(), name="analysis_list"),
    path("analysis/<int:pk>/delete/", delete_analysis, name="delete_analysis"),
    path("analyses/bulk-delete/", bulk_delete_pagespeed_analyses, name="bulk_delete_pagespeed_analyses"),
    path("extract-headers/", extract_headers_view, name="extract_headers"),
    path("header-analyses/", header_analysis_list, name="header_analysis_list"),
    path("header-analyses/bulk-delete/", bulk_delete_header_analyses, name="bulk_delete_header_analyses"),
    path("header-analysis/<int:pk>/", header_analysis_detail, name="header_analysis_detail"),
    path("header-analysis/<int:pk>/delete/", delete_header_analysis, name="delete_header_analysis"),
    path("image-alt-finder/", image_alt_finder, name="image_alt_finder"),
    path("image-alt-analyses/", image_alt_list, name="image_alt_list"),
    path("image-alt-analysis/<int:pk>/", image_alt_detail, name="image_alt_detail"),
    path("image-alt-analysis/<int:pk>/delete/", delete_image_alt_analysis, name="delete_image_alt_analysis"),
    path("image-alt-analyses/bulk-delete/", bulk_delete_image_alt_analyses, name="bulk_delete_image_alt_analyses"),
    path("keywords-finder/", keywords_finder, name="keywords_finder"),
    path("keywords-analyses/", keywords_list, name="keywords_list"),
    path("keywords-analysis/<int:pk>/", keywords_detail, name="keywords_detail"),
    path("keywords-analysis/<int:pk>/delete/", delete_keyword_analysis, name="delete_keyword_analysis"),
    path("keywords-analyses/bulk-delete/", bulk_delete_keyword_analyses, name="bulk_delete_keyword_analyses"),
    # Google Search Console OAuth
    path("connect-gsc/", connect_gsc, name="connect_gsc"),
    path("gsc-callback/", gsc_callback, name="gsc_callback"),
    path("disconnect-gsc/", disconnect_gsc, name="disconnect_gsc"),
    
    # AI Search / AEO Optimization
    path("ai-search/", ai_search_overview, name="ai_search_overview"),
    path("ai-search/audit/", ai_readiness_audit, name="ai_readiness_audit"),
    path("ai-search/audit/<int:pk>/", ai_readiness_detail, name="ai_readiness_detail"),
    path("ai-search/audit/<int:pk>/delete/", delete_ai_readiness, name="delete_ai_readiness"),
    path("ai-search/audit/bulk-delete/", bulk_delete_ai_readiness, name="bulk_delete_ai_readiness"),
    path("ai-search/questions/", ai_question_research, name="ai_question_research"),
    path("ai-search/opportunities/", ai_citation_opportunities, name="ai_citation_opportunities"),

    # PDF Reports
    path("reports/", pdf_reports_list, name="pdf_reports_list"),
    path("reports/generate/", generate_pdf_report, name="generate_pdf_report"),
    path("reports/<int:pk>/", pdf_report_detail, name="pdf_report_detail"),
    path("reports/<int:pk>/preview/", preview_pdf_report, name="preview_pdf_report"),
    path("reports/<int:pk>/download/", download_pdf_report, name="download_pdf_report"),
    path("reports/<int:pk>/delete/", delete_pdf_report, name="delete_pdf_report"),
    path("reports/bulk-delete/", bulk_delete_pdf_reports, name="bulk_delete_pdf_reports"),
    path("reports/<int:pk>/regenerate/", regenerate_pdf_report, name="regenerate_pdf_report"),
]

