# Generated by Django 6.0 on 2026-01-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagespeedanalysis',
            name='content_headers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
