# Generated by Django 6.0 on 2026-01-28 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_imagealtanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('total_keywords', models.IntegerField(default=0)),
                ('top_3_positions', models.IntegerField(default=0)),
                ('top_10_positions', models.IntegerField(default=0)),
                ('top_20_positions', models.IntegerField(default=0)),
                ('total_volume', models.IntegerField(default=0)),
                ('avg_position', models.FloatField(default=0)),
                ('keywords_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_k_user_id_595f79_idx'), models.Index(fields=['url'], name='dashboard_k_url_2743d3_idx')],
            },
        ),
    ]
