# Generated by Django 6.0 on 2026-01-28 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_keywordanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSCConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('properties', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GSC Connection',
                'verbose_name_plural': 'GSC Connections',
            },
        ),
    ]
