# Generated by Django 6.0 on 2026-02-15 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_gscconnection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('free', 'Free Report'), ('paid', 'Premium Report')], default='free', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('headers_data', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(upload_to='reports/%Y/%m/%d/')),
                ('include_recommendations', models.BooleanField(default=True)),
                ('include_charts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_reports', to='dashboard.imagealtanalysis')),
                ('keyword_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_reports', to='dashboard.keywordanalysis')),
                ('pagespeed_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_reports', to='dashboard.pagespeedanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_p_user_id_b8e0a7_idx'), models.Index(fields=['report_type'], name='dashboard_p_report__fa9246_idx')],
            },
        ),
    ]
