# Generated by Django 6.0 on 2026-08-18 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_headeranalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReadinessAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('overall_score', models.IntegerField(default=0)),
                ('answerability_score', models.IntegerField(default=0)),
                ('structure_score', models.IntegerField(default=0)),
                ('entity_score', models.IntegerField(default=0)),
                ('technical_score', models.IntegerField(default=0)),
                ('trust_score', models.IntegerField(default=0)),
                ('audit_results', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_readiness_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pdfreport',
            name='ai_readiness_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_reports', to='dashboard.aireadinessanalysis'),
        ),
        migrations.AddIndex(
            model_name='aireadinessanalysis',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_a_user_id_6d0dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='aireadinessanalysis',
            index=models.Index(fields=['url'], name='dashboard_a_url_89d05e_idx'),
        ),
    ]
