# Generated by Django 6.0 on 2026-03-15 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('default_property', models.CharField(blank=True, max_length=255)),
                ('preferred_date_range', models.CharField(choices=[('7d', 'Last 7 days'), ('28d', 'Last 28 days'), ('90d', 'Last 90 days')], default='28d', max_length=10)),
                ('receive_report_emails', models.BooleanField(default=True)),
                ('receive_alert_emails', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__email'],
            },
        ),
    ]
