# Generated by Django 6.0 on 2026-03-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='brand_client_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_device',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], default='mobile', max_length=10),
        ),
    ]
